CREATE TABLE applications (
 id UUID PRIMARY KEY,
 project_name VARCHAR(80) NOT NULL,
 author_name VARCHAR(80) NOT NULL,
 author_link TEXT NOT NULL,
 brief VARCHAR(20) NOT NULL,
 links JSONB NOT NULL CHECK (jsonb_typeof(links) = 'array'),
 cover_path TEXT NOT NULL,
 avatar_path TEXT NOT NULL,
 status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','approved','rejected')),
 created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
 reviewed_at TIMESTAMPTZ,
 reviewer_notes TEXT NOT NULL DEFAULT ''
);
CREATE INDEX applications_created_at ON applications (created_at DESC);
CREATE TABLE projects (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 application_id UUID UNIQUE REFERENCES applications(id),
 name VARCHAR(80) NOT NULL,
 author VARCHAR(80) NOT NULL,
 author_link TEXT NOT NULL,
 project_link TEXT NOT NULL,
 brief VARCHAR(20) NOT NULL,
 cover_path TEXT NOT NULL,
 avatar_path TEXT NOT NULL,
 created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
